[book]
authors = ["arHSM"]
language = "en"
multilingual = false
src = "src"
title = "Unofficial Discord Documentation"
description = "Theme for the Unofficial Discord Documentation"

[output.html]
default-theme = "dark"
preferred-dark-theme = "dark"
curly-quotes = true
copy-fonts = false
git-repository-url = "https://github.com/arHSM/ddocs"
git-repository-icon = "source"
edit-url-template = "https://github.com/arHSM/ddocs/edit/master/src/{path}"
site-url = "/ddocs/"

[output.html.print]
enable = false

[output.html.playground]
copyable = false
copy-js = false
